apiVersion: v1
kind: ConfigMap
metadata:
  name: omni-health-config
  namespace: omni-health
data:
  REDIS_HOST: redis
  RABBITMQ_HOST: rabbitmq
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
