apiVersion: v1
kind: Secret
metadata:
  name: omni-health-secrets
  namespace: omni-health
type: Opaque
stringData:
  DB_URL: jdbc:mysql://mysql:3306/omni_health
  DB_USERNAME: replace-me
  DB_PASSWORD: replace-me
  RABBITMQ_USERNAME: replace-me
  RABBITMQ_PASSWORD: replace-me
  SENTRY_DSN: replace-me
